version: '3.9'

services:
  web:
    build: .
    ports:
      - '7788:3000'
    volumes:
      - db-data:/app/prisma
    environment:
      NODE_ENV: production
      DATABASE_URL: "file:/app/prisma/dev.db"

volumes:
  db-data:
